//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_sJ7bIX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/analise_projeto_elaboracao_45AAA1BA_fa1a99bc_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_sJ7bIX_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/analise_projeto_elaboracao_45AAA1BA_fa1a99bc_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_tzuqgX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/impl_testes_elaboracao_5824897C_c94817e_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_lnzK4X_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/impl_testes_concepcao_6299D380_1755a595_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_lnzK4X_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/impl_testes_concepcao_6299D380_1755a595_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0w,_-uvaIX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/gerencia_validacao_CDF4368B_559a587e_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0w,_-uvaIX_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/gerencia_validacao_CDF4368B_559a587e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0wActivity"]="./../../PAAD/deliveryprocesses/resources/Construção_4F1185A4_22619e4f_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0wActivity"]="./../../PAAD/deliveryprocesses/resources/Concepção_757F1E16_48cf36c1_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0w,_6TeIsX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/requisitos_validacao_7F26D330_6ccf523_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0wActivity"]="./../../PAAD/deliveryprocesses/resources/Validação_A351A7F4_76a1c09f_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_yeMOgX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/requisitos_construcao_6E4A9088_a85e802b_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_yeMOgX_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/requisitos_construcao_6E4A9088_a85e802b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0wActivity"]="./../../PAAD/deliveryprocesses/resources/paad_740E5F57_740e5f57_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_vzlCYX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/gerencia_elaboracao_8BE78703_40577f05_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_vzlCYX_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/gerencia_elaboracao_8BE78703_40577f05_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_2QL5cX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/impl_testes_construcao_460953E6_801d4389_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_b8XAUX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/requisitos_concepcao_3C49BEB_b8806e00_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_b8XAUX_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/requisitos_concepcao_3C49BEB_b8806e00_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_3_WxAX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/gerencia_construcao_29183F0D_632c2eb0_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_3_WxAX_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/gerencia_construcao_29183F0D_632c2eb0_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0wActivity"]="./../../PAAD/deliveryprocesses/resources/Elaboração_24FFB03_d5a013ae_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0w,_89MkAH_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/impl_testes_validacao_62693C6F_ea0f5e62_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0w,_89MkAH_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/impl_testes_validacao_62693C6F_ea0f5e62_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_qmPa0X_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/requisitos_elaboracao_906D359E_44dd2da0_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_qmPa0X_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/requisitos_elaboracao_906D359E_44dd2da0_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_nrh9MX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/gerencia_concepcao_14EC4189_c9a8139e_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_nrh9MX_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/gerencia_concepcao_14EC4189_c9a8139e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_dVxDQX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/analise_projeto_concepcao_D5AF3EEE_8a6b1103_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_dVxDQX_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/analise_projeto_concepcao_D5AF3EEE_8a6b1103_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_z2HDsX_mEd61Af7ua88vmwActivity"]="./../../PAAD/deliveryprocesses/resources/analise_projeto_construcao_4CB298C2_86c68865_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_z2HDsX_mEd61Af7ua88vmwActivityDetail"]="./../../PAAD/deliveryprocesses/resources/analise_projeto_construcao_4CB298C2_86c68865_ActivityDetail.jpeg"
contentPage.processPage.elementUrls["_Ecp0oX_mEd62TNYWta-H0w"] = ["Concepção","PAAD/deliveryprocesses/Concepção_757F1E16.html"];
contentPage.processPage.elementUrls["_GzhI6H_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAAD/workproducts/diagrama_geral_cdus_40846856.html"];
contentPage.processPage.elementUrls["_kF1zcn_nEd61Af7ua88vmw"] = ["Consultar ou Entrevistar Cliente","PAAD/tasks/3_consultar_cliente_24317533.html"];
contentPage.processPage.elementUrls["_pJyOeH_nEd61Af7ua88vmw"] = ["Realizar a Disciplina de Implementação e Teste para o Caso de Uso Selecionado da SPRINT","PAAD/tasks/11_implementar_cdu_76E43FC.html"];
contentPage.processPage.elementUrls["_5pfAsDgzEeSw2dACrKM1QA"] = ["Realizar Analise de Evolução do Projeto","PAAD/deliveryprocesses/New Task Descriptor_658AFBE.html"];
contentPage.processPage.elementUrls["_GzhI7H_nEd61Af7ua88vmw"] = ["Documento de Arquitetura do Sistema","PAAD/workproducts/doc_arq_97F75231.html"];
contentPage.processPage.elementUrls["_Gss50H_oEd61Af7ua88vmw"] = ["Diagrama de Classes de Projeto (UML)","PAAD/workproducts/diagrama_de_classes_9DB6D23A.html"];
contentPage.processPage.elementUrls["_Gss5xH_oEd61Af7ua88vmw"] = ["Registrar Reuniões em Ata de Reunião","PAAD/tasks/8_registrar_em_ata_BF8B0498.html"];
contentPage.processPage.elementUrls["_pJyOfH_nEd61Af7ua88vmw"] = ["Analista","PAAD/roles/analista_64D8867D.html"];
contentPage.processPage.elementUrls["_6TeIsX_mEd61Af7ua88vmw"] = ["Requisitos Validação","PAAD/deliveryprocesses/requisitos_validacao_7F26D330.html"];
contentPage.processPage.elementUrls["_qc46MDcAEeSk0K6nPOXZgA"] = ["Realizar a Disciplina de Implementação e Teste para o Caso de Uso Selecionado da SPRINT","PAAD/deliveryprocesses/New Task Descriptor_3_F472548E.html"];
contentPage.processPage.elementUrls["_trKu8X_nEd61Af7ua88vmw"] = ["Especificar Ferramentas Inerentes ao Desenvolvimento","PAAD/tasks/16_especificar_ferramentas_desenv_F6E7B03.html"];
contentPage.processPage.elementUrls["_Gss52X_oEd61Af7ua88vmw"] = ["Plano de Iteração e Integração","PAAD/workproducts/plan_iteracao_BF0A4C84.html"];
contentPage.processPage.elementUrls["_89MkAH_mEd61Af7ua88vmw"] = ["Implementação e Testes Validação","PAAD/deliveryprocesses/impl_testes_validacao_62693C6F.html"];
contentPage.processPage.elementUrls["_Gss5y3_oEd61Af7ua88vmw"] = ["Arquiteto","PAAD/roles/arquiteto_E0E5CA76.html"];
contentPage.processPage.elementUrls["_4SNmLH_nEd61Af7ua88vmw"] = ["Códigos Fontes","PAAD/workproducts/codigos_fontes_9318F22A.html"];
contentPage.processPage.elementUrls["_LsMvEn_nEd61Af7ua88vmw"] = ["Especificar Ferramenta da Gerência","PAAD/tasks/3_especif_fer_ger_2F9E3480.html"];
contentPage.processPage.elementUrls["_Gss51H_oEd61Af7ua88vmw"] = ["Documento de Arquitetura do Sistema","PAAD/workproducts/doc_arq_97F75231.html"];
contentPage.processPage.elementUrls["_1s9bKH_nEd61Af7ua88vmw"] = ["Analista","PAAD/roles/analista_64D8867D.html"];
contentPage.processPage.elementUrls["_4SNmKH_nEd61Af7ua88vmw"] = ["Implementador e Testador","PAAD/roles/implementador_testador_33627EFA.html"];
contentPage.processPage.elementUrls["_trKvAX_nEd61Af7ua88vmw"] = ["Documento de Risco","PAAD/workproducts/doc_risco_5164A75.html"];
contentPage.processPage.elementUrls["_zkgYQDb7EeSk0K6nPOXZgA"] = ["Iniciar o Detalhamento dos Casos de Usos","PAAD/deliveryprocesses/New Task Descriptor_2_59A2690.html"];
contentPage.processPage.elementUrls["_trKvBn_nEd61Af7ua88vmw"] = ["Plano de Desenvolvimento de Software","PAAD/workproducts/plan_des_soft_5C893450.html"];
contentPage.processPage.elementUrls["_ZVMZcDcAEeSk0K6nPOXZgA"] = ["Escolher Casos de Uso para Validar a Arquitetura","PAAD/deliveryprocesses/New Task Descriptor_2_A9F735CD.html"];
contentPage.processPage.elementUrls["_trKu-X_nEd61Af7ua88vmw"] = ["Revisar Plano de Desenvolvimento de Software (PDS)","PAAD/tasks/19_revisar_plan_des_soft_1918617E.html"];
contentPage.processPage.elementUrls["_trKu_H_nEd61Af7ua88vmw"] = ["Implementador e Testador","PAAD/roles/implementador_testador_33627EFA.html"];
contentPage.processPage.elementUrls["_IG540X_mEd62TNYWta-H0w"] = ["Validação","PAAD/deliveryprocesses/Validação_A351A7F4.html"];
contentPage.processPage.elementUrls["_kF-9Yn_nEd61Af7ua88vmw"] = ["Documento de Visão","PAAD/workproducts/doc_visao_F3AF5E8B.html"];
contentPage.processPage.elementUrls["_trKvAH_nEd61Af7ua88vmw"] = ["Documento de Arquitetura do Sistema","PAAD/workproducts/doc_arq_97F75231.html"];
contentPage.processPage.elementUrls["_7mzjaH_nEd61Af7ua88vmw"] = ["Implementador e Testador","PAAD/roles/implementador_testador_33627EFA.html"];
contentPage.processPage.elementUrls["_Zpc1YDcEEeSk0K6nPOXZgA"] = ["Escolher caso de uso para ser implementado na iteração","PAAD/deliveryprocesses/New Task Descriptor_A2D9BCF6.html"];
contentPage.processPage.elementUrls["_7mzjbH_nEd61Af7ua88vmw"] = ["Ata de Reunião","PAAD/workproducts/ata_de_reuniao_35E68846.html"];
contentPage.processPage.elementUrls["_5HEGEDb0EeSk0K6nPOXZgA"] = ["Planejar Reuniões Diárias para equipe","PAAD/deliveryprocesses/Planejar Reuniões Diárias com Equipe do Projeto_25556FA7.html"];
contentPage.processPage.elementUrls["_-uvaIX_mEd61Af7ua88vmw"] = ["Gerência de Processo Validação","PAAD/deliveryprocesses/gerencia_validacao_CDF4368B.html"];
contentPage.processPage.elementUrls["_LsMvF3_nEd61Af7ua88vmw"] = ["Executar Reuniões com o Cliente","PAAD/tasks/7_executar_reunioes_5D09EC64.html"];
contentPage.processPage.elementUrls["_nrh9MX_mEd61Af7ua88vmw"] = ["Gerência de Processo Concepção","PAAD/deliveryprocesses/gerencia_concepcao_14EC4189.html"];
contentPage.processPage.elementUrls["_Gss5zn_oEd61Af7ua88vmw"] = ["Designer","PAAD/roles/designer_6129A4D4.html"];
contentPage.processPage.elementUrls["_EBlz0n_nEd61Af7ua88vmw"] = ["Definir Funcionalidades e as Restrições do Sistema","PAAD/tasks/3_definir_funcionalidades_495C0DF9.html"];
contentPage.processPage.elementUrls["_1s9bJ3_nEd61Af7ua88vmw"] = ["Gerente de Projetos","PAAD/roles/gerente_691919DB.html"];
contentPage.processPage.elementUrls["_kF1zd3_nEd61Af7ua88vmw"] = ["Projetista","PAAD/roles/projetista_2A96C9F0.html"];
contentPage.processPage.elementUrls["_1s9bIn_nEd61Af7ua88vmw"] = ["Identificar Mudanças nos Requisitos","PAAD/tasks/4_identificar_mudancas_requisitos_C1083FD9.html"];
contentPage.processPage.elementUrls["_GzhI53_nEd61Af7ua88vmw"] = ["Gerente de Projetos","PAAD/roles/gerente_691919DB.html"];
contentPage.processPage.elementUrls["_EBvk0H_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAAD/workproducts/diagrama_geral_cdus_40846856.html"];
contentPage.processPage.elementUrls["_Gss51X_oEd61Af7ua88vmw"] = ["Documento de Risco","PAAD/workproducts/doc_risco_5164A75.html"];
contentPage.processPage.elementUrls["_0evR4IelEd6d1_IKg3-6Ow"] = ["Planejar Reuniões com o Cliente","PAAD/tasks/6_plan_reunioes_cliente_F430169F.html"];
contentPage.processPage.elementUrls["_Gss50n_oEd61Af7ua88vmw"] = ["Diagrama de Interação de Objetos (UML) para o (s) Caso (s) de Uso (s) Implementado (s)","PAAD/workproducts/diagrama_interacao_BDB5B5DE.html"];
contentPage.processPage.elementUrls["_GzhI4n_nEd61Af7ua88vmw"] = ["Analisar Modelo de Caso de Uso","PAAD/tasks/7_analisar_mod_cdu_F4B0A66D.html"];
contentPage.processPage.elementUrls["_Gss523_oEd61Af7ua88vmw"] = ["Protótipos de Telas","PAAD/workproducts/prototipo_de_telas_C9A82C94.html"];
contentPage.processPage.elementUrls["_LsMvHX_nEd61Af7ua88vmw"] = ["Desenvolver Plano de Desenvolvimento de Software (PDS)","PAAD/tasks/14_desenvolver_plan_des_soft_8EBAC6C7.html"];
contentPage.processPage.elementUrls["_EBlz03_nEd61Af7ua88vmw"] = ["Dividir o Problema em Casos de Uso","PAAD/tasks/4_dividir_em_cdus_EDF6BE39.html"];
contentPage.processPage.elementUrls["_1s9bK3_nEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAAD/workproducts/especificacao_cdu_B6ECAA04.html"];
contentPage.processPage.elementUrls["_1s9bIX_nEd61Af7ua88vmw"] = ["Consultar ou Entrevistar Cliente","PAAD/tasks/3_consultar_cliente_24317533.html"];
contentPage.processPage.elementUrls["_dVxDQX_mEd61Af7ua88vmw"] = ["Análise e Projeto Concepção","PAAD/deliveryprocesses/analise_projeto_concepcao_D5AF3EEE.html"];
contentPage.processPage.elementUrls["_LsMvEH_nEd61Af7ua88vmw"] = ["Especificar Sistema Operacional","PAAD/tasks/1_especificar_so_3667405A.html"];
contentPage.processPage.elementUrls["_1s9bJH_nEd61Af7ua88vmw"] = ["Atualizar Documento de Visão e de Arquitetura de acordo com as mudanças propostas.","PAAD/tasks/6_atualizar_doc_visao_arquitetura_2FFD2CB1.html"];
contentPage.processPage.elementUrls["_FzrR8X_mEd62TNYWta-H0w"] = ["Elaboração","PAAD/deliveryprocesses/Elaboração_24FFB03.html"];
contentPage.processPage.elementUrls["_trKu8n_nEd61Af7ua88vmw"] = ["Instalar e/ou Configurar Softwares e Bibliotecas","PAAD/tasks/17_instalar_soft_bib_1FE16D58.html"];
contentPage.processPage.elementUrls["_7mzjZn_nEd61Af7ua88vmw"] = ["Revisar Plano de Desenvolvimento de Software (PDS)","PAAD/tasks/19_revisar_plan_des_soft_1918617E.html"];
contentPage.processPage.elementUrls["_pJyOcH_nEd61Af7ua88vmw"] = ["Revisar Documento de Visão, Arquitetura e Especificação de Casos de Uso","PAAD/tasks/13_revisar_doc_visao_Arquitetura_Especificações_E321A49F.html"];
contentPage.processPage.elementUrls["_4SNmKX_nEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAAD/workproducts/especificacao_cdu_B6ECAA04.html"];
contentPage.processPage.elementUrls["_7mzjan_nEd61Af7ua88vmw"] = ["Documento de Ambiente","PAAD/workproducts/doc_amb_2F1D7C6C.html"];
contentPage.processPage.elementUrls["_8tEv0IemEd6d1_IKg3-6Ow"] = ["Planejar Reuniões com o Cliente","PAAD/tasks/6_plan_reunioes_cliente_F430169F.html"];
contentPage.processPage.elementUrls["_trKu93_nEd61Af7ua88vmw"] = ["Apresentar Implementação Realizada","PAAD/tasks/18_apresentar_implementacao_2A7F4D68.html"];
contentPage.processPage.elementUrls["_LsMvKH_nEd61Af7ua88vmw"] = ["Plano de Iteração e Integração","PAAD/workproducts/plan_iteracao_BF0A4C84.html"];
contentPage.processPage.elementUrls["_Gss5z3_oEd61Af7ua88vmw"] = ["Códigos Fontes","PAAD/workproducts/codigos_fontes_9318F22A.html"];
contentPage.processPage.elementUrls["_EyzY4H_oEd61Af7ua88vmw"] = ["Planejar Testes Alfa em Ambiente de Desenvolvimento","PAAD/tasks/1_planejar_testes_alfa_81A356FD.html"];
contentPage.processPage.elementUrls["_kF1zdn_nEd61Af7ua88vmw"] = ["Realizar Análise e Projeto","PAAD/tasks/10_realizar_analise_e_projeto_7C84D7D9.html"];
contentPage.processPage.elementUrls["_7mzjZ3_nEd61Af7ua88vmw"] = ["Desenvolver Plano de Iteração e Integração (PI&amp;I)","PAAD/tasks/15_desenvolver_plan_iteracao_7D53DADD.html"];
contentPage.processPage.elementUrls["_7mzjZH_nEd61Af7ua88vmw"] = ["Registrar Reuniões em Ata de Reunião","PAAD/tasks/8_registrar_em_ata_BF8B0498.html"];
contentPage.processPage.elementUrls["_qmPa0X_mEd61Af7ua88vmw"] = ["Requisitos Elaboração","PAAD/deliveryprocesses/requisitos_elaboracao_906D359E.html"];
contentPage.processPage.elementUrls["_EyzY4X_oEd61Af7ua88vmw"] = ["Executar Testes Alfa em Build Estável no Ambiente de Desenvolvimento","PAAD/tasks/2_executar_testes_alfa_C66BF80A.html"];
contentPage.processPage.elementUrls["_kF1zcX_nEd61Af7ua88vmw"] = ["Iniciar implementação do (s) Caso (s) de Uso Escolhido (s) para Validar Arquitetura","PAAD/tasks/2_Implementar_cdu_escolhido_Arquitetura_137294DA.html"];
contentPage.processPage.elementUrls["_trKu-3_nEd61Af7ua88vmw"] = ["Gerente de Projetos","PAAD/roles/gerente_691919DB.html"];
contentPage.processPage.elementUrls["_Gss513_oEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAAD/workproducts/especificacao_cdu_B6ECAA04.html"];
contentPage.processPage.elementUrls["_Gss5wH_oEd61Af7ua88vmw"] = ["Identificar o Ambiente Necessário para o Funcionamento do Sistema a ser Implantado","PAAD/tasks/21_identificar_ambiente_E770DF91.html"];
contentPage.processPage.elementUrls["_EBlz13_nEd61Af7ua88vmw"] = ["Analista","PAAD/roles/analista_64D8867D.html"];
contentPage.processPage.elementUrls["_trKu-n_nEd61Af7ua88vmw"] = ["Desenvolver Plano de Iteração e Integração (PI&amp;I)","PAAD/tasks/15_desenvolver_plan_iteracao_7D53DADD.html"];
contentPage.processPage.elementUrls["_GzhI5H_nEd61Af7ua88vmw"] = ["Definir Arquitetura (Documento de Arquitetura do Sistema)","PAAD/tasks/9_elaborar_doc_arq_47CAEE1F.html"];
contentPage.processPage.elementUrls["_4SNmJn_nEd61Af7ua88vmw"] = ["Executar Implementação do Projeto","PAAD/tasks/12_executar_implementacao_DDBBCCC7.html"];
contentPage.processPage.elementUrls["_trKu_n_nEd61Af7ua88vmw"] = ["Documento de Ambiente","PAAD/workproducts/doc_amb_2F1D7C6C.html"];
contentPage.processPage.elementUrls["_7mzjcn_nEd61Af7ua88vmw"] = ["Plano de Iteração e Integração","PAAD/workproducts/plan_iteracao_BF0A4C84.html"];
contentPage.processPage.elementUrls["_1s9bKX_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAAD/workproducts/diagrama_geral_cdus_40846856.html"];
contentPage.processPage.elementUrls["_LsMvFX_nEd61Af7ua88vmw"] = ["Escrever Documento de Ambiente","PAAD/tasks/5_escrever_doc_amb_5970289.html"];
contentPage.processPage.elementUrls["_EyzY8X_oEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAAD/workproducts/especificacao_cdu_B6ECAA04.html"];
contentPage.processPage.elementUrls["_Gss5wX_oEd61Af7ua88vmw"] = ["Instalar Softwares Identificados","PAAD/tasks/22_instalar_softwares_DCC98D79.html"];
contentPage.processPage.elementUrls["_trKvB3_nEd61Af7ua88vmw"] = ["Plano de Iteração e Integração","PAAD/workproducts/plan_iteracao_BF0A4C84.html"];
contentPage.processPage.elementUrls["_sJ7bIX_mEd61Af7ua88vmw"] = ["Análise e Projeto Elaboração","PAAD/deliveryprocesses/analise_projeto_elaboracao_45AAA1BA.html"];
contentPage.processPage.elementUrls["_lnzK4X_mEd61Af7ua88vmw"] = ["Implementação e Testes Concepção","PAAD/deliveryprocesses/impl_testes_concepcao_6299D380.html"];
contentPage.processPage.elementUrls["_LsMvKX_nEd61Af7ua88vmw"] = ["Protótipos de Telas","PAAD/workproducts/prototipo_de_telas_C9A82C94.html"];
contentPage.processPage.elementUrls["_LsMvHn_nEd61Af7ua88vmw"] = ["Desenvolver Plano de Iteração e Integração (PI&amp;I)","PAAD/tasks/15_desenvolver_plan_iteracao_7D53DADD.html"];
contentPage.processPage.elementUrls["_EyzY5H_oEd61Af7ua88vmw"] = ["Iniciar Alterações de Modelagem em Disciplina de Análise e Projeto","PAAD/tasks/5_iniciar_alteracoes_de_modelagem_9F634E1A.html"];
contentPage.processPage.elementUrls["_LsMvEX_nEd61Af7ua88vmw"] = ["Especificar Ferramentas de Escritório","PAAD/tasks/2_especificar_ferramentas_4105206A.html"];
contentPage.processPage.elementUrls["_If81gn_nEd61Af7ua88vmw"] = ["Confeccionar um Protótipo contendo as Telas Iniciais do Novo Sistema","PAAD/tasks/10_confeccionar_prototipo_C0806ED7.html"];
contentPage.processPage.elementUrls["_kF1zeH_nEd61Af7ua88vmw"] = ["Arquiteto","PAAD/roles/arquiteto_E0E5CA76.html"];
contentPage.processPage.elementUrls["_7mzjYn_nEd61Af7ua88vmw"] = ["Escrever Documento de Ambiente","PAAD/tasks/5_escrever_doc_amb_5970289.html"];
contentPage.processPage.elementUrls["_3_WxAX_mEd61Af7ua88vmw"] = ["Gerência de Processo Construção","PAAD/deliveryprocesses/gerencia_construcao_29183F0D.html"];
contentPage.processPage.elementUrls["_1s9bJX_nEd61Af7ua88vmw"] = ["Realizar Análise e Projeto","PAAD/tasks/10_realizar_analise_e_projeto_7C84D7D9.html"];
contentPage.processPage.elementUrls["_EyzY63_oEd61Af7ua88vmw"] = ["Projetista","PAAD/roles/projetista_2A96C9F0.html"];
contentPage.processPage.elementUrls["_LsMvJX_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAAD/workproducts/diagrama_geral_cdus_40846856.html"];
contentPage.processPage.elementUrls["_pJyOhn_nEd61Af7ua88vmw"] = ["Códigos Fontes","PAAD/workproducts/codigos_fontes_9318F22A.html"];
contentPage.processPage.elementUrls["_LsMvJ3_nEd61Af7ua88vmw"] = ["Plano de Desenvolvimento de Software","PAAD/workproducts/plan_des_soft_5C893450.html"];
contentPage.processPage.elementUrls["_trKu9H_nEd61Af7ua88vmw"] = ["Executar Reuniões com o Cliente","PAAD/tasks/7_executar_reunioes_5D09EC64.html"];
contentPage.processPage.elementUrls["_LsMvFH_nEd61Af7ua88vmw"] = ["Instalar e/ou Configurar as Ferramentas","PAAD/tasks/4_inst_ferramentas_FAF92279.html"];
contentPage.processPage.elementUrls["_EyzY4n_oEd61Af7ua88vmw"] = ["Verificar se Necessita passar por Implementação ou se deve passar por Remodelagem","PAAD/tasks/3_verificar_necessidade_de_remodelagem_2FD6125D.html"];
contentPage.processPage.elementUrls["_Gss5yn_oEd61Af7ua88vmw"] = ["Implementador e Testador","PAAD/roles/implementador_testador_33627EFA.html"];
contentPage.processPage.elementUrls["_5SLTcDcAEeSk0K6nPOXZgA"] = ["Executar Implementação do Projeto","PAAD/deliveryprocesses/New Task Descriptor_4_59383B6A.html"];
contentPage.processPage.elementUrls["_Gss5zX_oEd61Af7ua88vmw"] = ["Analista","PAAD/roles/analista_64D8867D.html"];
contentPage.processPage.elementUrls["_trKu9n_nEd61Af7ua88vmw"] = ["Execução da Disciplina de Requisitos","PAAD/tasks/9_executar_requisitos_CA28E4A8.html"];
contentPage.processPage.elementUrls["_z2HDsX_mEd61Af7ua88vmw"] = ["Análise e Projeto Construção","PAAD/deliveryprocesses/analise_projeto_construcao_4CB298C2.html"];
contentPage.processPage.elementUrls["_pJyOeX_nEd61Af7ua88vmw"] = ["Ajustar a Arquitetura","PAAD/tasks/9_ajustar_arq_DA507C29.html"];
contentPage.processPage.elementUrls["_OjJZ4DcFEeSk0K6nPOXZgA"] = ["Executar Implementação do Projeto","PAAD/deliveryprocesses/New Task Descriptor_3_D1C66B83.html"];
contentPage.processPage.elementUrls["_pJyOhH_nEd61Af7ua88vmw"] = ["Diagrama de Interação de Objetos (UML) para o (s) Caso (s) de Uso (s) Implementado (s)","PAAD/workproducts/diagrama_interacao_BDB5B5DE.html"];
contentPage.processPage.elementUrls["_kF-9Y3_nEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAAD/workproducts/especificacao_cdu_B6ECAA04.html"];
contentPage.processPage.elementUrls["_EBvk0X_nEd61Af7ua88vmw"] = ["Documento de Visão","PAAD/workproducts/doc_visao_F3AF5E8B.html"];
contentPage.processPage.elementUrls["_pJyOdn_nEd61Af7ua88vmw"] = ["Elaborar Diagrama de Interação de Objetos","PAAD/tasks/7_elaborar_diagrama_de_interacao_E48CC0C3.html"];
contentPage.processPage.elementUrls["_6JnHMDb_EeSk0K6nPOXZgA"] = ["Iniciar implementação do (s) Caso (s) de Uso Escolhido (s) para Validar Arquitetura","PAAD/deliveryprocesses/New Task Descriptor_4F7A5F27.html"];
contentPage.processPage.elementUrls["_EyzY6X_oEd61Af7ua88vmw"] = ["Gerar Relatório com Dados Coletados","PAAD/tasks/8_gerar_relatorio_de_teste_beta_B03BC8B3.html"];
contentPage.processPage.elementUrls["_kF1zdH_nEd61Af7ua88vmw"] = ["Atualizar Diagrama de Casos de Uso e de Classes","PAAD/tasks/5_atualizar_diagramas_cdus_classes_CC35F2DC.html"];
contentPage.processPage.elementUrls["_Gss5xX_oEd61Af7ua88vmw"] = ["Nova Iteração para Ajustes","PAAD/tasks/25_nova_iteracao_ajustes_E3C67632.html"];
contentPage.processPage.elementUrls["_GzhI63_nEd61Af7ua88vmw"] = ["Ata de Reunião","PAAD/workproducts/ata_de_reuniao_35E68846.html"];
contentPage.processPage.elementUrls["_7mzjcH_nEd61Af7ua88vmw"] = ["Documento de Risco","PAAD/workproducts/doc_risco_5164A75.html"];
contentPage.processPage.elementUrls["_Jd7zkTcFEeSk0K6nPOXZgA"] = ["Realizar a Disciplina de Implementação e Teste para o Caso de Uso Selecionado da SPRINT","PAAD/deliveryprocesses/New Task Descriptor_2_AFD2C92E.html"];
contentPage.processPage.elementUrls["_1s9bI3_nEd61Af7ua88vmw"] = ["Atualizar Diagrama de Casos de Uso e de Classes","PAAD/tasks/5_atualizar_diagramas_cdus_classes_CC35F2DC.html"];
contentPage.processPage.elementUrls["_EBlz2H_nEd61Af7ua88vmw"] = ["Arquiteto","PAAD/roles/arquiteto_E0E5CA76.html"];
contentPage.processPage.elementUrls["_EBlz0X_nEd61Af7ua88vmw"] = ["Definir Escopo do Problema","PAAD/tasks/2_definir_escopo_D4B7CAF0.html"];
contentPage.processPage.elementUrls["_pJyOen_nEd61Af7ua88vmw"] = ["Redefinir toda a Arquitetura","PAAD/tasks/8_redefinir_arq_ACB690D8.html"];
contentPage.processPage.elementUrls["_pJyOg3_nEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAAD/workproducts/especificacao_cdu_B6ECAA04.html"];
contentPage.processPage.elementUrls["_7imOQX_mEd61Af7ua88vmw"] = ["Análise e Projeto Validação","PAAD/deliveryprocesses/analise_projeto_validacao_1E5A6C4.html"];
contentPage.processPage.elementUrls["_FKPHETg0EeSw2dACrKM1QA"] = ["Realizara Disciplina de Análise e Projeto da Fase de Contrução","PAAD/deliveryprocesses/New Task Descriptor_2_99D96079.html"];
contentPage.processPage.elementUrls["_Gss5w3_oEd61Af7ua88vmw"] = ["Reunir-se para Apresentar o Sistema Final","PAAD/tasks/24_apresentar_sistema_AD9EB88F.html"];
contentPage.processPage.elementUrls["_Gss50X_oEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAAD/workproducts/diagrama_geral_cdus_40846856.html"];
contentPage.processPage.elementUrls["_trKvA3_nEd61Af7ua88vmw"] = ["Ata de Reunião","PAAD/workproducts/ata_de_reuniao_35E68846.html"];
contentPage.processPage.elementUrls["_GzhI5X_nEd61Af7ua88vmw"] = ["Arquiteto","PAAD/roles/arquiteto_E0E5CA76.html"];
contentPage.processPage.elementUrls["_LsMvI3_nEd61Af7ua88vmw"] = ["Documento de Visão","PAAD/workproducts/doc_visao_F3AF5E8B.html"];
contentPage.processPage.elementUrls["_LsMvJn_nEd61Af7ua88vmw"] = ["Ata de Reunião","PAAD/workproducts/ata_de_reuniao_35E68846.html"];
contentPage.processPage.elementUrls["_zBvsMDnqEeSQFudhAXKiDQ"] = ["Atualizar Diagrama de Casos de Uso e de Classes","PAAD/deliveryprocesses/New Task Descriptor_2_D96A2411.html"];
contentPage.processPage.elementUrls["_vzlCYX_mEd61Af7ua88vmw"] = ["Gerência de Processo Elaboração","PAAD/deliveryprocesses/gerencia_elaboracao_8BE78703.html"];
contentPage.processPage.elementUrls["_LsMvJH_nEd61Af7ua88vmw"] = ["Documento de Ambiente","PAAD/workproducts/doc_amb_2F1D7C6C.html"];
contentPage.processPage.elementUrls["_1s9bKn_nEd61Af7ua88vmw"] = ["Documento de Visão","PAAD/workproducts/doc_visao_F3AF5E8B.html"];
contentPage.processPage.elementUrls["_kF1zcH_nEd61Af7ua88vmw"] = ["Escolher Casos de Uso para Validar a Arquitetura","PAAD/tasks/1_escolher_cdus_9B029ED2.html"];
contentPage.processPage.elementUrls["_pJyOf3_nEd61Af7ua88vmw"] = ["Implementador e Testador","PAAD/roles/implementador_testador_33627EFA.html"];
contentPage.processPage.elementUrls["_Gss5yX_oEd61Af7ua88vmw"] = ["Gerente de Projetos","PAAD/roles/gerente_691919DB.html"];
contentPage.processPage.elementUrls["_trKvBH_nEd61Af7ua88vmw"] = ["Códigos Fontes","PAAD/workproducts/codigos_fontes_9318F22A.html"];
contentPage.processPage.elementUrls["_LsMvGX_nEd61Af7ua88vmw"] = ["Execução da Disciplina de Requisitos","PAAD/tasks/9_executar_requisitos_CA28E4A8.html"];
contentPage.processPage.elementUrls["_trKu_3_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAAD/workproducts/diagrama_geral_cdus_40846856.html"];
contentPage.processPage.elementUrls["_GzhI6X_nEd61Af7ua88vmw"] = ["Documento de Visão","PAAD/workproducts/doc_visao_F3AF5E8B.html"];
contentPage.processPage.elementUrls["_If81g3_nEd61Af7ua88vmw"] = ["Designer","PAAD/roles/designer_6129A4D4.html"];
contentPage.processPage.elementUrls["_EyzY7X_oEd61Af7ua88vmw"] = ["Códigos Fontes","PAAD/workproducts/codigos_fontes_9318F22A.html"];
contentPage.processPage.elementUrls["_trKu9X_nEd61Af7ua88vmw"] = ["Registrar Reuniões em Ata de Reunião","PAAD/tasks/8_registrar_em_ata_BF8B0498.html"];
contentPage.processPage.elementUrls["_kF1zeX_nEd61Af7ua88vmw"] = ["Gerente de Projetos","PAAD/roles/gerente_691919DB.html"];
contentPage.processPage.elementUrls["_IutWEDcFEeSk0K6nPOXZgA"] = ["Escolher caso de uso para ser implementado na iteração","PAAD/deliveryprocesses/New Task Descriptor_DA74A2B6.html"];
contentPage.processPage.elementUrls["_kF-9YH_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAAD/workproducts/diagrama_geral_cdus_40846856.html"];
contentPage.processPage.elementUrls["_trKu83_nEd61Af7ua88vmw"] = ["Escrever Documento de Ambiente","PAAD/tasks/5_escrever_doc_amb_5970289.html"];
contentPage.processPage.elementUrls["_LsMvFn_nEd61Af7ua88vmw"] = ["Planejar Reuniões com o Cliente","PAAD/tasks/6_plan_reunioes_cliente_F430169F.html"];
contentPage.processPage.elementUrls["_kF-9YX_nEd61Af7ua88vmw"] = ["Documento de Arquitetura do Sistema","PAAD/workproducts/doc_arq_97F75231.html"];
contentPage.processPage.elementUrls["_Gss5yH_oEd61Af7ua88vmw"] = ["Realizar Comemoração de Fim de Projeto","PAAD/tasks/26_comemoracao_fim_C150F27.html"];
contentPage.processPage.elementUrls["_LsMvIX_nEd61Af7ua88vmw"] = ["Documento de Arquitetura do Sistema","PAAD/workproducts/doc_arq_97F75231.html"];
contentPage.processPage.elementUrls["_GsTjEX_mEd62TNYWta-H0w"] = ["Construção","PAAD/deliveryprocesses/Construção_4F1185A4.html"];
contentPage.processPage.elementUrls["_EBlz0H_nEd61Af7ua88vmw"] = ["Cliente Define o Projeto a ser Desenvolvido","PAAD/tasks/1_definir_projeto_109F4117.html"];
contentPage.processPage.elementUrls["_EBlz1H_nEd61Af7ua88vmw"] = ["Classificar Casos de Uso por Módulo de Sistema ","PAAD/tasks/5_classificar_cdus_A0EC2832.html"];
contentPage.processPage.elementUrls["_1s9bJn_nEd61Af7ua88vmw"] = ["Projetista","PAAD/roles/projetista_2A96C9F0.html"];
contentPage.processPage.elementUrls["_pJyOfn_nEd61Af7ua88vmw"] = ["Projetista","PAAD/roles/projetista_2A96C9F0.html"];
contentPage.processPage.elementUrls["_Gss5xn_oEd61Af7ua88vmw"] = ["Revisar Plano de Desenvolvimento de Software (PDS)","PAAD/tasks/19_revisar_plan_des_soft_1918617E.html"];
contentPage.processPage.elementUrls["_4SNmK3_nEd61Af7ua88vmw"] = ["Diagrama de Classes de Projeto (UML)","PAAD/workproducts/diagrama_de_classes_9DB6D23A.html"];
contentPage.processPage.elementUrls["_Gss52H_oEd61Af7ua88vmw"] = ["Plano de Desenvolvimento de Software","PAAD/workproducts/plan_des_soft_5C893450.html"];
contentPage.processPage.elementUrls["_b8XAUX_mEd61Af7ua88vmw"] = ["Requisitos Concepção","PAAD/deliveryprocesses/requisitos_concepcao_3C49BEB.html"];
contentPage.processPage.elementUrls["_EBlz1X_nEd61Af7ua88vmw"] = ["Descrever Brevemente Casos de Uso","PAAD/tasks/6_descrever_cdus_55A3AA0F.html"];
contentPage.processPage.elementUrls["_1s9bIH_nEd61Af7ua88vmw"] = ["Iniciar o Detalhamento dos Casos de Usos","PAAD/tasks/0_detalhar_cdu_90F4B6B2.html"];
contentPage.processPage.elementUrls["_acgZETb7EeSk0K6nPOXZgA"] = ["Escolher Casos de Usos para Validar a Arquitetura","PAAD/deliveryprocesses/New Task Descriptor_1F34E95E.html"];
contentPage.processPage.elementUrls["_7mzjb3_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAAD/workproducts/diagrama_geral_cdus_40846856.html"];
contentPage.processPage.elementUrls["_pJyOhX_nEd61Af7ua88vmw"] = ["Diagrama de Classes de Projeto (UML)","PAAD/workproducts/diagrama_de_classes_9DB6D23A.html"];
contentPage.processPage.elementUrls["_yeMOgX_mEd61Af7ua88vmw"] = ["Requisitos Construção","PAAD/deliveryprocesses/requisitos_construcao_6E4A9088.html"];
contentPage.processPage.elementUrls["_GzhI43_nEd61Af7ua88vmw"] = ["Reunir Equipe e Cliente para Avaliação da Arquitetura Candidata","PAAD/tasks/8_reunir_equipe_42D185E7.html"];
contentPage.processPage.elementUrls["_Gss503_oEd61Af7ua88vmw"] = ["Documento de Ambiente","PAAD/workproducts/doc_amb_2F1D7C6C.html"];
contentPage.processPage.elementUrls["_kF1zc3_nEd61Af7ua88vmw"] = ["Identificar Mudanças nos Requisitos","PAAD/tasks/4_identificar_mudancas_requisitos_C1083FD9.html"];
contentPage.processPage.elementUrls["_7mzjY3_nEd61Af7ua88vmw"] = ["Executar Reuniões com o Cliente ao Fim da Iteração com o Protótipo Desenvolvido","PAAD/tasks/20_executar_reunioes_cliente_E4666229.html"];
contentPage.processPage.elementUrls["_pJyOfX_nEd61Af7ua88vmw"] = ["Arquiteto","PAAD/roles/arquiteto_E0E5CA76.html"];
contentPage.processPage.elementUrls["_LsMvGH_nEd61Af7ua88vmw"] = ["Registrar Reuniões em Ata de Reunião","PAAD/tasks/8_registrar_em_ata_BF8B0498.html"];
contentPage.processPage.elementUrls["_kF1zen_nEd61Af7ua88vmw"] = ["Analista","PAAD/roles/analista_64D8867D.html"];
contentPage.processPage.elementUrls["_4SNmKn_nEd61Af7ua88vmw"] = ["Diagrama de Interação de Objetos (UML) para o (s) Caso (s) de Uso (s) Implementado (s)","PAAD/workproducts/diagrama_interacao_BDB5B5DE.html"];
contentPage.processPage.elementUrls["_WzrssTcFEeSk0K6nPOXZgA"] = ["Revisar Documento de Visão, Arquitetura e Especificação de Casos de Uso","PAAD/deliveryprocesses/New Task Descriptor_4_80F528ED.html"];
contentPage.processPage.elementUrls["_LsMvGn_nEd61Af7ua88vmw"] = ["Apresentar Artefatos ao Cliente","PAAD/tasks/12_apresentar_artefatos_B8C1F8BE.html"];
contentPage.processPage.elementUrls["_UI-EcIelEd6d1_IKg3-6Ow"] = ["Planejar Reuniões com o Cliente","PAAD/tasks/6_plan_reunioes_cliente_F430169F.html"];
contentPage.processPage.elementUrls["_EyzY6n_oEd61Af7ua88vmw"] = ["Implementador e Testador","PAAD/roles/implementador_testador_33627EFA.html"];
contentPage.processPage.elementUrls["_trKvAn_nEd61Af7ua88vmw"] = ["Documento de Visão","PAAD/workproducts/doc_visao_F3AF5E8B.html"];
contentPage.processPage.elementUrls["_tzuqgX_mEd61Af7ua88vmw"] = ["Implementação e Testes Elaboração","PAAD/deliveryprocesses/impl_testes_elaboracao_5824897C.html"];
contentPage.processPage.elementUrls["_EyzY5X_oEd61Af7ua88vmw"] = ["Executar Builds Necessários, Integrar (caso necessário) e criar um Release","PAAD/tasks/6_executar_build_B49BA0CA.html"];
contentPage.processPage.elementUrls["_If81hH_nEd61Af7ua88vmw"] = ["Protótipos de Telas","PAAD/workproducts/prototipo_de_telas_C9A82C94.html"];
contentPage.processPage.elementUrls["_7mzjbn_nEd61Af7ua88vmw"] = ["Plano de Desenvolvimento de Software","PAAD/workproducts/plan_des_soft_5C893450.html"];
contentPage.processPage.elementUrls["_Gss51n_oEd61Af7ua88vmw"] = ["Documento de Visão","PAAD/workproducts/doc_visao_F3AF5E8B.html"];
contentPage.processPage.elementUrls["_7mzjcX_nEd61Af7ua88vmw"] = ["Documento de Visão","PAAD/workproducts/doc_visao_F3AF5E8B.html"];
contentPage.processPage.elementUrls["_EyzY73_oEd61Af7ua88vmw"] = ["Diagrama de Classes de Projeto (UML)","PAAD/workproducts/diagrama_de_classes_9DB6D23A.html"];
contentPage.processPage.elementUrls["_EyzY8H_oEd61Af7ua88vmw"] = ["Diagrama de Interação de Objetos (UML) para o (s) Caso (s) de Uso (s) Implementado (s)","PAAD/workproducts/diagrama_interacao_BDB5B5DE.html"];
contentPage.processPage.elementUrls["_trKu_X_nEd61Af7ua88vmw"] = ["Analista","PAAD/roles/analista_64D8867D.html"];
contentPage.processPage.elementUrls["_f7tAMX_lEd62TNYWta-H0w"] = ["Processo Acadêmico Ágil Distribuído - PAAD","PAAD/deliveryprocesses/paad_740E5F57.html"];
contentPage.processPage.elementUrls["_EyzY43_oEd61Af7ua88vmw"] = ["Implementar Correção de Erros","PAAD/tasks/4_implementar_correcoes_5DBA916F.html"];
contentPage.processPage.elementUrls["_EBlz1n_nEd61Af7ua88vmw"] = ["Stakeholders","PAAD/roles/stakeholders_7A8005C5.html"];
contentPage.processPage.elementUrls["_pJyOgH_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAAD/workproducts/diagrama_geral_cdus_40846856.html"];
contentPage.processPage.elementUrls["_7mzjaX_nEd61Af7ua88vmw"] = ["Gerente de Projetos","PAAD/roles/gerente_691919DB.html"];
contentPage.processPage.elementUrls["_Gss5zH_oEd61Af7ua88vmw"] = ["Projetista","PAAD/roles/projetista_2A96C9F0.html"];
contentPage.processPage.elementUrls["_EBvk0n_nEd61Af7ua88vmw"] = ["Documento de Risco","PAAD/workproducts/doc_risco_5164A75.html"];
contentPage.processPage.elementUrls["_Gss5wn_oEd61Af7ua88vmw"] = ["Implantar o Sistema","PAAD/tasks/23_implantar_sistema_495BBE9F.html"];
contentPage.processPage.elementUrls["_7mzja3_nEd61Af7ua88vmw"] = ["Códigos Fontes","PAAD/workproducts/codigos_fontes_9318F22A.html"];
contentPage.processPage.elementUrls["_G8xYQH_3Ed61Af7ua88vmw"] = ["Elaborar Diagrama de Interação de Objetos","PAAD/tasks/7_elaborar_diagrama_de_interacao_E48CC0C3.html"];
contentPage.processPage.elementUrls["_LsMvH3_nEd61Af7ua88vmw"] = ["Gerente de Projetos","PAAD/roles/gerente_691919DB.html"];
contentPage.processPage.elementUrls["_pJyOgX_nEd61Af7ua88vmw"] = ["Documento de Arquitetura do Sistema","PAAD/workproducts/doc_arq_97F75231.html"];
contentPage.processPage.elementUrls["_2QL5cX_mEd61Af7ua88vmw"] = ["Implementação e Testes Construção","PAAD/deliveryprocesses/impl_testes_construcao_460953E6.html"];
contentPage.processPage.elementUrls["_LsMvHH_nEd61Af7ua88vmw"] = ["Execução da Disciplina de Requisitos Sobre o Documento de Visão","PAAD/tasks/13_exec_req_doc_visao_841CE6B7.html"];
contentPage.processPage.elementUrls["_Gss53H_oEd61Af7ua88vmw"] = ["Ata de Reunião","PAAD/workproducts/ata_de_reuniao_35E68846.html"];
contentPage.processPage.elementUrls["_LsMvIH_nEd61Af7ua88vmw"] = ["Analista","PAAD/roles/analista_64D8867D.html"];
contentPage.processPage.elementUrls["_Gss5x3_oEd61Af7ua88vmw"] = ["Desenvolver Plano de Iteração e Integração (PI&amp;I)","PAAD/tasks/15_desenvolver_plan_iteracao_7D53DADD.html"];
contentPage.processPage.elementUrls["_LsMvIn_nEd61Af7ua88vmw"] = ["Documento de Risco","PAAD/workproducts/doc_risco_5164A75.html"];
contentPage.processPage.elementUrls["_4SNmJ3_nEd61Af7ua88vmw"] = ["Projetista","PAAD/roles/projetista_2A96C9F0.html"];
contentPage.processPage.elementUrls["_pJyOgn_nEd61Af7ua88vmw"] = ["Documento de Visão","PAAD/workproducts/doc_visao_F3AF5E8B.html"];
contentPage.processPage.elementUrls["_kF1zdX_nEd61Af7ua88vmw"] = ["Atualizar Documento de Visão e de Arquitetura de acordo com as mudanças propostas.","PAAD/tasks/6_atualizar_doc_visao_arquitetura_2FFD2CB1.html"];
